### PR TITLE
Configurable default avatar URL

### PR DESCRIPTION
**Pull request by Oumph**
No need for dev platforms (or external uses from other projects) to get default avatar from our prod platform.

### CODE REVIEW

**Comment by Oumph** [comment]
Replace https://github.com/linuxfrorg/img-LinuxFr.org/pull/1

**Comment by Trim** [comment]
Could we put the new default SVG image in this repository instead of the old PNG ? It renders better and the Dark Reader Firefox extension is working better with the SVG :)

**Comment by Trim** [comment]
> Could we put the new default SVG image in this repository instead of the old PNG ? It renders better and the Dark Reader Firefox extension is working better with the SVG :)

Oh, I've just seen your comment on the #1 request:

> (and the change from this MR would be done during the deployment by configuration)

I don't see the point of importing the old png in this repository ? The SVG file is a better format for rendering at any size and its changes will be better followed by git.

**Comment by Oumph** [comment]
Deployed on alpha.

**Pull request merged**
